services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  php:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  vue-app:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    ports:
      - 8081:8080
    volumes:
      - ./frontend/app:/src
    tty: true
    environment:
      - NODE_ENV=development
volumes:
  db-data: